-- EduNexus MySQL 8.0+ ERD schema
-- Purpose: import into MySQL Workbench / DBeaver / dbdiagram.io to generate the ERD.
-- This is DDL only; the SQL Server all-in-one script remains the executable demo database.
CREATE DATABASE IF NOT EXISTS edunexus CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE edunexus;

CREATE TABLE roles (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) NOT NULL UNIQUE, description VARCHAR(255));
CREATE TABLE users (id CHAR(36) PRIMARY KEY, email VARCHAR(256) NOT NULL UNIQUE, password_hash VARCHAR(512), display_name VARCHAR(150) NOT NULL, avatar_url VARCHAR(512), auth_provider VARCHAR(20) NOT NULL DEFAULT 'Local', google_subject VARCHAR(128) UNIQUE, is_email_verified BOOLEAN NOT NULL DEFAULT FALSE, is_active BOOLEAN NOT NULL DEFAULT TRUE, ai_token_quota BIGINT, ai_token_used BIGINT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME, last_login_at DATETIME);
CREATE TABLE user_roles (user_id CHAR(36) NOT NULL, role_id INT NOT NULL, PRIMARY KEY(user_id,role_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE);
CREATE TABLE login_sessions (id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, device_info VARCHAR(256), ip_address VARCHAR(64), created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME, revoked_at DATETIME, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE password_reset_tokens (id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, token_hash VARCHAR(512) NOT NULL, expires_at DATETIME NOT NULL, used_at DATETIME, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE email_verification_tokens (id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, token_hash VARCHAR(512) NOT NULL, expires_at DATETIME NOT NULL, used_at DATETIME, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE course_groups (id CHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, description VARCHAR(1000), created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE courses (id CHAR(36) PRIMARY KEY, title VARCHAR(250) NOT NULL, description VARCHAR(2000), owner_sme_id CHAR(36), status VARCHAR(20) NOT NULL DEFAULT 'Draft', is_visible BOOLEAN NOT NULL DEFAULT TRUE, version INT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME, published_at DATETIME, FOREIGN KEY(owner_sme_id) REFERENCES users(id));
CREATE TABLE course_group_courses (course_group_id CHAR(36) NOT NULL, course_id CHAR(36) NOT NULL, PRIMARY KEY(course_group_id,course_id), FOREIGN KEY(course_group_id) REFERENCES course_groups(id) ON DELETE CASCADE, FOREIGN KEY(course_id) REFERENCES courses(id) ON DELETE CASCADE);
CREATE TABLE course_group_managers (course_group_id CHAR(36) NOT NULL, user_id CHAR(36) NOT NULL, assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, assigned_by_id CHAR(36), PRIMARY KEY(course_group_id,user_id), FOREIGN KEY(course_group_id) REFERENCES course_groups(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(assigned_by_id) REFERENCES users(id));
CREATE TABLE modules (id CHAR(36) PRIMARY KEY, course_id CHAR(36) NOT NULL, title VARCHAR(250) NOT NULL, order_index INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(course_id,order_index), FOREIGN KEY(course_id) REFERENCES courses(id) ON DELETE CASCADE);
CREATE TABLE lessons (id CHAR(36) PRIMARY KEY, module_id CHAR(36) NOT NULL, title VARCHAR(250) NOT NULL, order_index INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME, UNIQUE(module_id,order_index), FOREIGN KEY(module_id) REFERENCES modules(id) ON DELETE CASCADE);
CREATE TABLE lesson_contents (id CHAR(36) PRIMARY KEY, lesson_id CHAR(36) NOT NULL, content_type VARCHAR(20) NOT NULL, markdown_text LONGTEXT, youtube_url VARCHAR(512), video_summary LONGTEXT, file_url VARCHAR(512), file_name VARCHAR(256), order_index INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(lesson_id) REFERENCES lessons(id) ON DELETE CASCADE);
CREATE TABLE ai_lesson_drafts (id CHAR(36) PRIMARY KEY, lesson_id CHAR(36), created_by_id CHAR(36) NOT NULL, source_text LONGTEXT, generated_text LONGTEXT, status VARCHAR(20) NOT NULL DEFAULT 'Pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(lesson_id) REFERENCES lessons(id), FOREIGN KEY(created_by_id) REFERENCES users(id));

CREATE TABLE questions (id CHAR(36) PRIMARY KEY, module_id CHAR(36) NOT NULL, content LONGTEXT NOT NULL, explanation LONGTEXT, difficulty VARCHAR(20) NOT NULL DEFAULT 'Medium', status VARCHAR(20) NOT NULL DEFAULT 'Active', created_by_id CHAR(36), created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(module_id) REFERENCES modules(id) ON DELETE CASCADE, FOREIGN KEY(created_by_id) REFERENCES users(id));
CREATE TABLE question_options (id CHAR(36) PRIMARY KEY, question_id CHAR(36) NOT NULL, content VARCHAR(1000) NOT NULL, is_correct BOOLEAN NOT NULL DEFAULT FALSE, order_index INT NOT NULL DEFAULT 0, FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE);
CREATE TABLE ai_question_drafts (id CHAR(36) PRIMARY KEY, module_id CHAR(36), created_by_id CHAR(36) NOT NULL, source_text LONGTEXT, generated_json LONGTEXT, status VARCHAR(20) NOT NULL DEFAULT 'Pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(module_id) REFERENCES modules(id), FOREIGN KEY(created_by_id) REFERENCES users(id));
CREATE TABLE flashcard_groups (id CHAR(36) PRIMARY KEY, module_id CHAR(36) NOT NULL, name VARCHAR(200) NOT NULL, order_index INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(module_id) REFERENCES modules(id) ON DELETE CASCADE);
CREATE TABLE flashcards (id CHAR(36) PRIMARY KEY, group_id CHAR(36), module_id CHAR(36) NOT NULL, front_text VARCHAR(500) NOT NULL, back_text VARCHAR(500) NOT NULL, order_index INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(group_id) REFERENCES flashcard_groups(id), FOREIGN KEY(module_id) REFERENCES modules(id) ON DELETE CASCADE);
CREATE TABLE ai_flashcard_drafts (id CHAR(36) PRIMARY KEY, module_id CHAR(36), created_by_id CHAR(36) NOT NULL, source_text LONGTEXT, generated_json LONGTEXT, status VARCHAR(20) NOT NULL DEFAULT 'Pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(module_id) REFERENCES modules(id), FOREIGN KEY(created_by_id) REFERENCES users(id));
CREATE TABLE flashcard_progress (id CHAR(36) PRIMARY KEY, flashcard_id CHAR(36) NOT NULL, student_id CHAR(36) NOT NULL, is_learned BOOLEAN NOT NULL DEFAULT FALSE, last_reviewed_at DATETIME, UNIQUE(flashcard_id,student_id), FOREIGN KEY(flashcard_id) REFERENCES flashcards(id) ON DELETE CASCADE, FOREIGN KEY(student_id) REFERENCES users(id));

CREATE TABLE classes (id CHAR(36) PRIMARY KEY, course_id CHAR(36) NOT NULL, name VARCHAR(250) NOT NULL, teacher_id CHAR(36), start_date DATE, end_date DATE, max_students INT NOT NULL DEFAULT 500, fee DECIMAL(12,2) NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'Open', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(course_id) REFERENCES courses(id), FOREIGN KEY(teacher_id) REFERENCES users(id));
CREATE TABLE class_materials (id CHAR(36) PRIMARY KEY, class_id CHAR(36) NOT NULL, title VARCHAR(250) NOT NULL, content_type VARCHAR(20) NOT NULL, url VARCHAR(512), markdown_text LONGTEXT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE);
CREATE TABLE class_students (id CHAR(36) PRIMARY KEY, class_id CHAR(36) NOT NULL, student_id CHAR(36) NOT NULL, joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, status VARCHAR(20) NOT NULL DEFAULT 'Active', UNIQUE(class_id,student_id), FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE, FOREIGN KEY(student_id) REFERENCES users(id));
CREATE TABLE assignments (id CHAR(36) PRIMARY KEY, module_id CHAR(36) NOT NULL, class_id CHAR(36), title VARCHAR(250) NOT NULL, prompt_markdown LONGTEXT, due_date DATETIME, max_chars INT NOT NULL DEFAULT 20000, status VARCHAR(20) NOT NULL DEFAULT 'Draft', created_by_id CHAR(36), created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(module_id) REFERENCES modules(id) ON DELETE CASCADE, FOREIGN KEY(class_id) REFERENCES classes(id), FOREIGN KEY(created_by_id) REFERENCES users(id));
CREATE TABLE rubric_criteria (id CHAR(36) PRIMARY KEY, assignment_id CHAR(36) NOT NULL, name VARCHAR(250) NOT NULL, weight DECIMAL(5,2) NOT NULL, max_score DECIMAL(5,2) NOT NULL, order_index INT NOT NULL DEFAULT 0, FOREIGN KEY(assignment_id) REFERENCES assignments(id) ON DELETE CASCADE);
CREATE TABLE submissions (id CHAR(36) PRIMARY KEY, assignment_id CHAR(36) NOT NULL, student_id CHAR(36) NOT NULL, content_text LONGTEXT, submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, status VARCHAR(20) NOT NULL DEFAULT 'Submitted', ai_total_score DECIMAL(6,2), final_score DECIMAL(6,2), teacher_comment LONGTEXT, confirmed_by_id CHAR(36), confirmed_at DATETIME, UNIQUE(assignment_id,student_id), FOREIGN KEY(assignment_id) REFERENCES assignments(id) ON DELETE CASCADE, FOREIGN KEY(student_id) REFERENCES users(id), FOREIGN KEY(confirmed_by_id) REFERENCES users(id));
CREATE TABLE submission_criterion_scores (id CHAR(36) PRIMARY KEY, submission_id CHAR(36) NOT NULL, criterion_id CHAR(36) NOT NULL, ai_score DECIMAL(5,2), final_score DECIMAL(5,2), comment LONGTEXT, FOREIGN KEY(submission_id) REFERENCES submissions(id) ON DELETE CASCADE, FOREIGN KEY(criterion_id) REFERENCES rubric_criteria(id));

CREATE TABLE quizzes (id CHAR(36) PRIMARY KEY, student_id CHAR(36) NOT NULL, course_id CHAR(36), title VARCHAR(250), question_count INT NOT NULL DEFAULT 0, difficulty VARCHAR(20), created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(student_id) REFERENCES users(id), FOREIGN KEY(course_id) REFERENCES courses(id));
CREATE TABLE quiz_questions (id CHAR(36) PRIMARY KEY, quiz_id CHAR(36) NOT NULL, question_id CHAR(36) NOT NULL, order_index INT NOT NULL DEFAULT 0, FOREIGN KEY(quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE, FOREIGN KEY(question_id) REFERENCES questions(id));
CREATE TABLE quiz_attempts (id CHAR(36) PRIMARY KEY, quiz_id CHAR(36) NOT NULL, student_id CHAR(36) NOT NULL, started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, submitted_at DATETIME, score DECIMAL(6,2), FOREIGN KEY(quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE, FOREIGN KEY(student_id) REFERENCES users(id));
CREATE TABLE quiz_attempt_answers (id CHAR(36) PRIMARY KEY, attempt_id CHAR(36) NOT NULL, question_id CHAR(36) NOT NULL, selected_option_id CHAR(36), is_correct BOOLEAN, FOREIGN KEY(attempt_id) REFERENCES quiz_attempts(id) ON DELETE CASCADE, FOREIGN KEY(question_id) REFERENCES questions(id), FOREIGN KEY(selected_option_id) REFERENCES question_options(id));

CREATE TABLE course_prices (id CHAR(36) PRIMARY KEY, course_id CHAR(36) NOT NULL, price DECIMAL(12,2) NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(course_id) REFERENCES courses(id) ON DELETE CASCADE);
CREATE TABLE packages (id CHAR(36) PRIMARY KEY, course_group_id CHAR(36) NOT NULL, name VARCHAR(200) NOT NULL, duration_months INT NOT NULL, price DECIMAL(12,2) NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(course_group_id) REFERENCES course_groups(id) ON DELETE CASCADE);
CREATE TABLE package_subscriptions (id CHAR(36) PRIMARY KEY, package_id CHAR(36) NOT NULL, student_id CHAR(36) NOT NULL, start_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'Active', FOREIGN KEY(package_id) REFERENCES packages(id), FOREIGN KEY(student_id) REFERENCES users(id));
CREATE TABLE access_grants (id CHAR(36) PRIMARY KEY, student_id CHAR(36) NOT NULL, course_id CHAR(36), grant_type VARCHAR(10) NOT NULL, source_ref_id CHAR(36), granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME, is_revoked BOOLEAN NOT NULL DEFAULT FALSE, FOREIGN KEY(student_id) REFERENCES users(id), FOREIGN KEY(course_id) REFERENCES courses(id));
CREATE TABLE payments (id CHAR(36) PRIMARY KEY, student_id CHAR(36) NOT NULL, amount DECIMAL(12,2) NOT NULL, provider VARCHAR(20) NOT NULL, purchase_type VARCHAR(10) NOT NULL, ref_id CHAR(36), provider_txn_id VARCHAR(128) UNIQUE, status VARCHAR(20) NOT NULL DEFAULT 'Pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, paid_at DATETIME, FOREIGN KEY(student_id) REFERENCES users(id));

CREATE TABLE lesson_progress (id CHAR(36) PRIMARY KEY, lesson_id CHAR(36) NOT NULL, student_id CHAR(36) NOT NULL, is_completed BOOLEAN NOT NULL DEFAULT FALSE, completed_at DATETIME, UNIQUE(lesson_id,student_id), FOREIGN KEY(lesson_id) REFERENCES lessons(id) ON DELETE CASCADE, FOREIGN KEY(student_id) REFERENCES users(id));
CREATE TABLE ai_usage_logs (id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, task_type VARCHAR(50) NOT NULL, tokens_used BIGINT NOT NULL DEFAULT 0, duration_ms INT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE activity_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id CHAR(36), action VARCHAR(100) NOT NULL, entity_type VARCHAR(100), entity_id VARCHAR(64), result VARCHAR(50), detail LONGTEXT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE notifications (id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, type VARCHAR(50) NOT NULL, title VARCHAR(250) NOT NULL, message LONGTEXT, channel VARCHAR(20) NOT NULL DEFAULT 'InApp', is_read BOOLEAN NOT NULL DEFAULT FALSE, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE system_configs (config_key VARCHAR(100) PRIMARY KEY, config_value LONGTEXT NOT NULL, description VARCHAR(500), updated_by_id CHAR(36), updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(updated_by_id) REFERENCES users(id));

CREATE INDEX ix_courses_owner_sme ON courses(owner_sme_id);
CREATE INDEX ix_access_grants_student ON access_grants(student_id,is_revoked,expires_at);
CREATE INDEX ix_payments_student ON payments(student_id);
CREATE INDEX ix_notifications_user ON notifications(user_id,is_read);
CREATE INDEX ix_flashcards_group ON flashcards(group_id);
