namespace EduNexus.Api.Infrastructure.Youtube;

/// <summary>Nguồn văn bản lấy được từ video.</summary>
public enum TranscriptSource
{
    /// <summary>Phụ đề thật của video (endpoint timedtext).</summary>
    Captions,

    /// <summary>Tiêu đề + mô tả lấy qua YouTube Data API v3 — dùng khi không lấy được phụ đề.</summary>
    Metadata
}

public record TranscriptResult(
    string VideoId,
    string Text,
    string LanguageCode,
    bool IsAutoGenerated,
    TranscriptSource Source);

/// <summary>
/// Lấy văn bản mô tả nội dung video YouTube — đầu vào cho màn Lesson Text Extract.
/// </summary>
public interface IYoutubeTranscriptService
{
    /// <summary>
    /// Thử lần lượt: phụ đề (timedtext) → metadata (Data API v3).
    /// Trả null nếu cả hai đều không có — khi đó UI cho SME dán transcript thủ công.
    /// </summary>
    Task<TranscriptResult?> TryGetTranscriptAsync(string youtubeUrl, CancellationToken ct = default);

    /// <summary>Tách videoId từ các dạng URL youtube.com/watch, youtu.be, /embed, /shorts. Null nếu không phải link YouTube.</summary>
    string? TryParseVideoId(string youtubeUrl);
}
