using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using EduNexus.Api.Infrastructure.Ai;
using Microsoft.Extensions.Options;

namespace EduNexus.Api.Infrastructure.Youtube;

/// <summary>
/// Lấy văn bản của video YouTube theo 2 tầng:
///
/// 1. Phụ đề qua endpoint timedtext (đọc captionTracks trong trang video).
///    YouTube hiện chặn phần lớn request server-side (đòi proof-of-origin token của trình duyệt)
///    nên tầng này thường không lấy được — vẫn giữ vì khi chạy được thì cho transcript đầy đủ nhất.
///
/// 2. YouTube Data API v3 (videos.list) — lấy tiêu đề + mô tả bằng API key.
///    Đây là tầng chạy ổn định trên thực tế.
///
/// Cả hai thất bại → trả null, UI cho SME dán transcript thủ công.
/// </summary>
public partial class YoutubeTranscriptService : IYoutubeTranscriptService
{
    private static readonly string[] PreferredLanguages = { "vi", "en" };

    private readonly HttpClient _http;
    private readonly AiOptions.YoutubeOptions _options;
    private readonly ILogger<YoutubeTranscriptService> _logger;

    public YoutubeTranscriptService(HttpClient http, IOptions<AiOptions> options, ILogger<YoutubeTranscriptService> logger)
    {
        _http = http;
        _options = options.Value.Youtube;
        _logger = logger;
    }

    public string? TryParseVideoId(string youtubeUrl)
    {
        if (string.IsNullOrWhiteSpace(youtubeUrl)) return null;
        if (!Uri.TryCreate(youtubeUrl.Trim(), UriKind.Absolute, out var uri)) return null;

        var host = uri.Host.StartsWith("www.", StringComparison.OrdinalIgnoreCase) ? uri.Host[4..] : uri.Host;
        var id = host.ToLowerInvariant() switch
        {
            "youtu.be" => uri.AbsolutePath.Trim('/'),
            "youtube.com" or "m.youtube.com" or "youtube-nocookie.com" => FromYoutubeComPath(uri),
            _ => null
        };

        return id is not null && VideoIdPattern().IsMatch(id) ? id : null;
    }

    private static string? FromYoutubeComPath(Uri uri)
    {
        var segments = uri.AbsolutePath.Trim('/').Split('/');
        if (segments.Length >= 2 && segments[0] is "embed" or "shorts" or "live")
            return segments[1];

        return System.Web.HttpUtility.ParseQueryString(uri.Query)["v"];
    }

    public async Task<TranscriptResult?> TryGetTranscriptAsync(string youtubeUrl, CancellationToken ct = default)
    {
        var videoId = TryParseVideoId(youtubeUrl);
        if (videoId is null) return null;

        return await TryGetCaptionsAsync(videoId, ct)
            ?? await TryGetMetadataAsync(videoId, ct);
    }

    // ---------------------------------------------------------------- Tầng 1: phụ đề

    private async Task<TranscriptResult?> TryGetCaptionsAsync(string videoId, CancellationToken ct)
    {
        try
        {
            var html = await _http.GetStringAsync($"https://www.youtube.com/watch?v={videoId}", ct);

            var track = SelectTrack(html);
            if (track is null) return null;

            var json = await _http.GetStringAsync($"{track.Value.BaseUrl}&fmt=json3", ct);
            var text = ParseJson3(json);
            if (string.IsNullOrWhiteSpace(text)) return null;

            return new TranscriptResult(videoId, text, track.Value.LanguageCode, track.Value.IsAutoGenerated, TranscriptSource.Captions);
        }
        catch (Exception ex) when (ex is HttpRequestException or TaskCanceledException or JsonException)
        {
            _logger.LogInformation("Không lấy được phụ đề của video {VideoId} ({Reason}) — chuyển sang YouTube Data API.",
                videoId, ex.GetType().Name);
            return null;
        }
    }

    private (string BaseUrl, string LanguageCode, bool IsAutoGenerated)? SelectTrack(string html)
    {
        var match = CaptionTracksPattern().Match(html);
        if (!match.Success) return null;

        using var doc = JsonDocument.Parse(match.Groups[1].Value);

        var tracks = doc.RootElement.EnumerateArray()
            .Select(t => (
                BaseUrl: t.TryGetProperty("baseUrl", out var b) ? b.GetString() : null,
                LanguageCode: t.TryGetProperty("languageCode", out var l) ? l.GetString() ?? "" : "",
                // kind = "asr" nghĩa là phụ đề tự động nhận dạng giọng nói, chất lượng thấp hơn phụ đề người tải lên.
                IsAutoGenerated: t.TryGetProperty("kind", out var k) && k.GetString() == "asr"))
            .Where(t => !string.IsNullOrEmpty(t.BaseUrl))
            .ToList();

        if (tracks.Count == 0) return null;

        foreach (var lang in PreferredLanguages)
        {
            var manual = tracks.FirstOrDefault(t => t.LanguageCode.StartsWith(lang) && !t.IsAutoGenerated);
            if (manual.BaseUrl is not null) return (manual.BaseUrl!, manual.LanguageCode, manual.IsAutoGenerated);

            var auto = tracks.FirstOrDefault(t => t.LanguageCode.StartsWith(lang));
            if (auto.BaseUrl is not null) return (auto.BaseUrl!, auto.LanguageCode, auto.IsAutoGenerated);
        }

        var first = tracks[0];
        return (first.BaseUrl!, first.LanguageCode, first.IsAutoGenerated);
    }

    /// <summary>Định dạng json3: events[].segs[].utf8 — ghép lại thành văn bản liền mạch.</summary>
    private static string ParseJson3(string json)
    {
        if (string.IsNullOrWhiteSpace(json)) return string.Empty;

        using var doc = JsonDocument.Parse(json);
        if (!doc.RootElement.TryGetProperty("events", out var events)) return string.Empty;

        var sb = new StringBuilder();
        foreach (var ev in events.EnumerateArray())
        {
            if (!ev.TryGetProperty("segs", out var segs)) continue;

            foreach (var seg in segs.EnumerateArray())
            {
                if (seg.TryGetProperty("utf8", out var utf8))
                    sb.Append(utf8.GetString());
            }
        }

        return WhitespacePattern().Replace(sb.ToString(), " ").Trim();
    }

    // ---------------------------------------------------------------- Tầng 2: YouTube Data API v3

    private async Task<TranscriptResult?> TryGetMetadataAsync(string videoId, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(_options.ApiKey))
        {
            _logger.LogInformation("Chưa cấu hình Ai:Youtube:ApiKey — bỏ qua YouTube Data API.");
            return null;
        }

        try
        {
            var url = $"https://www.googleapis.com/youtube/v3/videos?part=snippet&id={videoId}&key={_options.ApiKey}";
            var json = await _http.GetStringAsync(url, ct);

            using var doc = JsonDocument.Parse(json);
            if (!doc.RootElement.TryGetProperty("items", out var items) || items.GetArrayLength() == 0)
            {
                _logger.LogWarning("YouTube Data API không trả về video {VideoId}.", videoId);
                return null;
            }

            var snippet = items[0].GetProperty("snippet");
            var title = snippet.TryGetProperty("title", out var t) ? t.GetString() ?? "" : "";
            var description = snippet.TryGetProperty("description", out var d) ? d.GetString() ?? "" : "";
            var channel = snippet.TryGetProperty("channelTitle", out var c) ? c.GetString() ?? "" : "";
            var language = snippet.TryGetProperty("defaultAudioLanguage", out var l) ? l.GetString() ?? "und" : "und";

            var text = $"Tiêu đề: {title}\nKênh: {channel}\n\nMô tả:\n{description}".Trim();

            return new TranscriptResult(videoId, text, language, false, TranscriptSource.Metadata);
        }
        catch (Exception ex) when (ex is HttpRequestException or TaskCanceledException or JsonException or KeyNotFoundException)
        {
            _logger.LogWarning(ex, "Gọi YouTube Data API thất bại cho video {VideoId}.", videoId);
            return null;
        }
    }

    // ---------------------------------------------------------------- Regex

    [GeneratedRegex(@"""captionTracks"":(\[.*?\])")]
    private static partial Regex CaptionTracksPattern();

    [GeneratedRegex(@"^[A-Za-z0-9_-]{11}$")]
    private static partial Regex VideoIdPattern();

    [GeneratedRegex(@"\s+")]
    private static partial Regex WhitespacePattern();
}
